dist: trusty
sudo: false
language: csharp
mono: none
dotnet: 1.0.1
services:
  - docker
script:    
  - dotnet restore ./VaderSharp.Test/VaderSharp.Test.csproj
  - dotnet test ./VaderSharp.Test/VaderSharp.Test.csproj
